### ISSUE TITLE
SSH Key Access?

### ISSUE THREAD

**Issue by zoeblair** [pantheon-systems/terminus-github-actions#15]
I think I have to add an ssh key somewhere to authenticate with terminus. I can list sites fine but can't yet run terminus commands on specific sites.  Probably this should be added to the readme too.

**Comment by kporras07** [comment]
You're right. Terminus authenticates with machine token for regular commands; but for commands like drush or wp-cli, you need a ssh key for them to work. In order to setup ssh keys, you could use a different github actions like https://github.com/marketplace/actions/install-ssh-key or https://github.com/marketplace/actions/webfactory-ssh-agent

**Comment by zoeblair** [comment]
Ok thank you. I've added this step before running pantheon-systems/terminus-github-actions@main and it's working now. 
```
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
```
